apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterpolice-operator-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role-cluster
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["create", "get", "list", "update", "delete","patch","watch"]
  - apiGroups: ["operators.chaigitsy-1.github.com"]
    resources: ["clusterpolices"]
    verbs: ["watch", "list", "create", "get", "update", "delete", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-role-namespaced
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["create", "get", "list", "update", "delete","patch","watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["operators.chaigitsy-1.github.com"]
    resources: ["clusterpolices"]
    verbs: ["watch", "list", "create", "get", "update", "delete", "patch"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: clusterpolice-operator-account
    namespace: <replace with right namespace value>
#REPLACE WITH RIGHT NAMESPACE HERE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: clusterpolice-operator-account

