apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      testhealth: "yes"
  template:
    metadata:
      labels:
        app: nginx
        testhealth: "yes"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    testhealth: "yes"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

