apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: clusterpolices.operators.chaigitsy-1.github.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: operators.chaigitsy-1.github.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                port:
                  type: integer
                labels:
                  type: string
                healthcheckendpoint:
                  type: string
                interval:
                  type: integer
                timeout:
                  type: integer
                retries:
                  type: integer
                maillist:
                  type: array
                  items:
                    type: string
                smtpdetails:
                  type: string
                smtpport:
                  type: integer
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: clusterpolices
    # singular name to be used as an alias on the CLI and for display
    singular: clusterpolice
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ClusterPolice
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - clpo